/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.segmax.portlet.sample.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.segmax.portlet.sample.model.Appointment;
import com.segmax.portlet.sample.service.AppointmentService;
import com.segmax.portlet.sample.service.persistence.AppointmentPersistence;
import com.segmax.portlet.sample.service.persistence.SchedulePersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the appointment remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.segmax.portlet.sample.service.impl.AppointmentServiceImpl}.
 * </p>
 *
 * @author segmax
 * @see com.segmax.portlet.sample.service.impl.AppointmentServiceImpl
 * @see com.segmax.portlet.sample.service.AppointmentServiceUtil
 * @generated
 */
public abstract class AppointmentServiceBaseImpl extends BaseServiceImpl
	implements AppointmentService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.segmax.portlet.sample.service.AppointmentServiceUtil} to access the appointment remote service.
	 */

	/**
	 * Returns the appointment local service.
	 *
	 * @return the appointment local service
	 */
	public com.segmax.portlet.sample.service.AppointmentLocalService getAppointmentLocalService() {
		return appointmentLocalService;
	}

	/**
	 * Sets the appointment local service.
	 *
	 * @param appointmentLocalService the appointment local service
	 */
	public void setAppointmentLocalService(
		com.segmax.portlet.sample.service.AppointmentLocalService appointmentLocalService) {
		this.appointmentLocalService = appointmentLocalService;
	}

	/**
	 * Returns the appointment remote service.
	 *
	 * @return the appointment remote service
	 */
	public com.segmax.portlet.sample.service.AppointmentService getAppointmentService() {
		return appointmentService;
	}

	/**
	 * Sets the appointment remote service.
	 *
	 * @param appointmentService the appointment remote service
	 */
	public void setAppointmentService(
		com.segmax.portlet.sample.service.AppointmentService appointmentService) {
		this.appointmentService = appointmentService;
	}

	/**
	 * Returns the appointment persistence.
	 *
	 * @return the appointment persistence
	 */
	public AppointmentPersistence getAppointmentPersistence() {
		return appointmentPersistence;
	}

	/**
	 * Sets the appointment persistence.
	 *
	 * @param appointmentPersistence the appointment persistence
	 */
	public void setAppointmentPersistence(
		AppointmentPersistence appointmentPersistence) {
		this.appointmentPersistence = appointmentPersistence;
	}

	/**
	 * Returns the schedule local service.
	 *
	 * @return the schedule local service
	 */
	public com.segmax.portlet.sample.service.ScheduleLocalService getScheduleLocalService() {
		return scheduleLocalService;
	}

	/**
	 * Sets the schedule local service.
	 *
	 * @param scheduleLocalService the schedule local service
	 */
	public void setScheduleLocalService(
		com.segmax.portlet.sample.service.ScheduleLocalService scheduleLocalService) {
		this.scheduleLocalService = scheduleLocalService;
	}

	/**
	 * Returns the schedule remote service.
	 *
	 * @return the schedule remote service
	 */
	public com.segmax.portlet.sample.service.ScheduleService getScheduleService() {
		return scheduleService;
	}

	/**
	 * Sets the schedule remote service.
	 *
	 * @param scheduleService the schedule remote service
	 */
	public void setScheduleService(
		com.segmax.portlet.sample.service.ScheduleService scheduleService) {
		this.scheduleService = scheduleService;
	}

	/**
	 * Returns the schedule persistence.
	 *
	 * @return the schedule persistence
	 */
	public SchedulePersistence getSchedulePersistence() {
		return schedulePersistence;
	}

	/**
	 * Sets the schedule persistence.
	 *
	 * @param schedulePersistence the schedule persistence
	 */
	public void setSchedulePersistence(SchedulePersistence schedulePersistence) {
		this.schedulePersistence = schedulePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Appointment.class;
	}

	protected String getModelClassName() {
		return Appointment.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = appointmentPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.segmax.portlet.sample.service.AppointmentLocalService.class)
	protected com.segmax.portlet.sample.service.AppointmentLocalService appointmentLocalService;
	@BeanReference(type = com.segmax.portlet.sample.service.AppointmentService.class)
	protected com.segmax.portlet.sample.service.AppointmentService appointmentService;
	@BeanReference(type = AppointmentPersistence.class)
	protected AppointmentPersistence appointmentPersistence;
	@BeanReference(type = com.segmax.portlet.sample.service.ScheduleLocalService.class)
	protected com.segmax.portlet.sample.service.ScheduleLocalService scheduleLocalService;
	@BeanReference(type = com.segmax.portlet.sample.service.ScheduleService.class)
	protected com.segmax.portlet.sample.service.ScheduleService scheduleService;
	@BeanReference(type = SchedulePersistence.class)
	protected SchedulePersistence schedulePersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private AppointmentServiceClpInvoker _clpInvoker = new AppointmentServiceClpInvoker();
}