/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.segmax.portlet.sample.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Appointment service. Represents a row in the &quot;KT_Appointment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.segmax.portlet.sample.model.impl.AppointmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.segmax.portlet.sample.model.impl.AppointmentImpl}.
 * </p>
 *
 * @author segmax
 * @see Appointment
 * @see com.segmax.portlet.sample.model.impl.AppointmentImpl
 * @see com.segmax.portlet.sample.model.impl.AppointmentModelImpl
 * @generated
 */
public interface AppointmentModel extends BaseModel<Appointment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a appointment model instance should use the {@link Appointment} interface instead.
	 */

	/**
	 * Returns the primary key of this appointment.
	 *
	 * @return the primary key of this appointment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this appointment.
	 *
	 * @param primaryKey the primary key of this appointment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the app ID of this appointment.
	 *
	 * @return the app ID of this appointment
	 */
	public long getAppId();

	/**
	 * Sets the app ID of this appointment.
	 *
	 * @param appId the app ID of this appointment
	 */
	public void setAppId(long appId);

	/**
	 * Returns the app date of this appointment.
	 *
	 * @return the app date of this appointment
	 */
	public Date getAppDate();

	/**
	 * Sets the app date of this appointment.
	 *
	 * @param appDate the app date of this appointment
	 */
	public void setAppDate(Date appDate);

	/**
	 * Returns the surgery ID of this appointment.
	 *
	 * @return the surgery ID of this appointment
	 */
	public long getSurgeryId();

	/**
	 * Sets the surgery ID of this appointment.
	 *
	 * @param surgeryId the surgery ID of this appointment
	 */
	public void setSurgeryId(long surgeryId);

	/**
	 * Returns the visitor ID of this appointment.
	 *
	 * @return the visitor ID of this appointment
	 */
	public long getVisitorId();

	/**
	 * Sets the visitor ID of this appointment.
	 *
	 * @param visitorId the visitor ID of this appointment
	 */
	public void setVisitorId(long visitorId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.segmax.portlet.sample.model.Appointment appointment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.segmax.portlet.sample.model.Appointment> toCacheModel();

	@Override
	public com.segmax.portlet.sample.model.Appointment toEscapedModel();

	@Override
	public com.segmax.portlet.sample.model.Appointment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}